version: '2'

services:

  product-details-database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: testpw
      MYSQL_DATABASE: products
  
  product-prices-database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: testpw
      MYSQL_DATABASE: products
   
  product-details-service:
    image: maven
    links:
      - product-details-database:mysql
    working_dir: /application
    volumes:
      - ../product-details-service:/application
      - ~/.m2:/root/.m2
    ports:
      - 8080
    command: sh -c 'sleep 10 && mvn spring-boot:run'
  
  product-prices-service:
    image: maven
    links:
      - product-prices-database:mysql
    working_dir: /application
    volumes:
      - ../product-prices-service:/application
      - ~/.m2:/root/.m2
    ports:
      - 8080
    command: sh -c 'sleep 10 && mvn spring-boot:run'
  
  product-offer-service:
    image: maven
    links:
      - product-details-service
      - product-prices-service
    working_dir: /application
    volumes:
      - ../product-offer-service:/application
      - ~/.m2:/root/.m2
    ports:
      - 8080
    command: sh -c 'sleep 15 && mvn spring-boot:run'