version: '2'

services:

  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
    environment:
      - NEO4J_AUTH=none

  elasticsearch:
    image: elasticsearch
    ports:
      - 9200:9200

  kibana:
    image: kibana
    links:
      - elasticsearch
    ports:
      - 5601:5601

  product-details-database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: testpw
      MYSQL_DATABASE: products
  
  product-prices-database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: testpw
      MYSQL_DATABASE: products
   
  product-details-service:
    image: maven
    links:
      - product-details-database:mysql
    working_dir: /application
    volumes:
      - ../product-details-service:/application
      - ~/.m2:/root/.m2
    ports:
      - 8081:8080
    command: sh -c 'sleep 10 && mvn spring-boot:run'
  
  product-prices-service:
    image: maven
    links:
      - product-prices-database:mysql
    working_dir: /application
    volumes:
      - ../product-prices-service:/application
      - ~/.m2:/root/.m2
    ports:
      - 8082:8080
    command: sh -c 'sleep 10 && mvn spring-boot:run'
  
  product-offer-service:
    image: maven
    links:
      - product-details-service
      - product-prices-service
    working_dir: /application
    volumes:
      - ../product-offer-service:/application
      - ~/.m2:/root/.m2
    ports:
      - 8083:8080
    command: mvn spring-boot:run

  product-details-logstash:
    build: ./logstash
    links:
      - elasticsearch
    volumes_from:
      - product-details-service
    environment:
      HOST_NAME: product-details-service

  product-prices-logstash:
    build: ./logstash
    links:
      - elasticsearch
    volumes_from:
      - product-prices-service
    environment:
      HOST_NAME: product-prices-service

  product-offers-logstash:
    build: ./logstash
    links:
      - elasticsearch
    volumes_from:
      - product-offer-service
    environment:
      HOST_NAME: product-offer-service

  access-log-scanner:
    image: maven
    working_dir: /application
    volumes:
      - ../access-log-scanner:/application
      - ~/.m2:/root/.m2
    ports:
      - 8091:8080
    links:
      - elasticsearch
      - neo4j
    command: mvn spring-boot:run

  ansible-scanner:
    image: maven
    working_dir: /application
    volumes:
      - ../ansible-scanner:/application
      - ~/.m2:/root/.m2
    ports:
      - 8092:8080
    links:
      - neo4j
    command: mvn spring-boot:run

  integration-engine:
    image: maven
    working_dir: /application
    volumes:
      - ../integration-engine:/application
      - ~/.m2:/root/.m2
      - ./integration-engine/rules.yml:/application/rules.yml
    ports:
      - 8090:8080
    links:
      - neo4j
    command: mvn spring-boot:run